add_rules("mode.debug", "mode.release")

-- target("vdestructor")
--     add_toolchains("gcc")
--     set_kind("binary")
--     add_files("vdestructor/main.cc")
-- target_end()

-- target("virtual_func")
--     set_kind("binary")
--     add_files("virtual_func/main.cc")
-- target_end()

-- target("modtest")
--     add_toolchains("gcc")
--     set_kind("binary")
--     add_files("modtest.ixx")
--     add_files("moduletest.cc")
-- target_end()
add_languages("c++20")
target("target")
    add_toolchains("gcc")
    add_files("modtest.ixx")
    add_files("moduletest.cc")
    set_kind("binary")
