-- target("vdestructor")
--     add_toolchains("gcc")
--     set_kind("binary")
--     add_files("vdestructor/main.cc")
-- target_end()

-- target("virtual_func")
--     set_kind("binary")
--     add_files("virtual_func/main.cc")
-- target_end()

-- target("modtest")
-- add_languages("c++20")
--     set_kind("binary")
--     add_files("module.ixx")
--     add_files("module.cc")
--     add_files("main.cc")
-- target_end()
target("test")
    set_kind("binary")
    set_targetdir("./target/")
    add_languages("c++23")
    add_files("./test.cc")
target_end()