import numpy as np
def printf(index,array):
    print(f"{index}.{array}")
#array可以创建一个任意维度的数组
A=np.array([[1,2,3],[1,2,3]])
printf(1,A)
#zeros可以创建一个全零数组，参数代表形状
A=np.zeros((2,3))
printf(2,A)
#ones可以创建一个全1数组，参数代表形状
A=np.ones((2,3))
printf(3,A)
#可以用shape来获取数组形状
printf(4,A.shape)
#创建一个递增或者递减的数组
A=np.arange(1,9)
printf(5,A)
#创建等距分布的数组
A=np.linspace(1,2,11)
printf(6,A)
#上述创建方式后面可以跟上dtype来指明类型，也可以使用astype来转型
A=np.zeros((2,3),dtype=np.int64)
printf(7,A)
#创建随机生成的数组
A=np.random.rand(2,3)
printf(8,A)
#------------------------------------------
#运算部分
#可以直接进行加减乘除会将对应的数字加减乘除如：
A=np.array([1,2,3])
B=np.array([1,2,3])
printf(9,A+B)
printf(10,A-B)
printf(11,A*B)
printf(12,A/B)
#点乘
A=np.array([1,2,3])
B=np.array([1,2,3])
printf(13,np.dot(A,B))
#矩阵乘法
A=np.array([1,2,3])
B=np.array([[1],[2],[3]])
printf(14,A@B)
#对每个数依次运算
A=np.array([1,2,3])
printf(15,np.sqrt(A))
printf(16,np.sin(A))
printf(17,np.cos(A))
printf(18,np.tan(A))
printf(19,np.log(A))
printf(20,np.power(A,2))
#乘标量
A=np.array([1,2,3])
printf(21,A*5)
#形状不同会先将A变成[[1,2,3],[1,2,3],[1,2,3]]将b变成[[1,1,1],[2,2,2],[3,3,3]]然后运算
A=np.array([1,2,3])
B=np.array([[1],[2],[3]])
printf(22,A+B)
#获取最大最小元素
A=np.array([1,2,3])
printf(23,A.max())
printf(24,A.min())
#获取最大最小元素索引
A=np.array([1,2,3])
printf(23,A.argmax())
printf(24,A.argmin())
#求和
A=np.array([1,2,3])
printf(25,A.sum())
#平均值
A=np.array([1,2,3])
printf(26,A.mean())
#中位数
A=np.array([1,2,3])
printf(27,np.median(A))
#方差与标准差
A=np.array([1,2,3])
printf(28,A.var())
printf(29,A.std())
#对于以上函数可以使用axis指定是行操作还是列操作
A=np.array([[1,2,3],[1,2,3]])
printf(30,A.sum(axis=0))
printf(31,A.sum(axis=1))
#还可以使用与python的下标一样的方法来获取，但可以添加条件，与和或要使用按位与和按位或如：
A=np.array([1,2,3])
printf(32,A[(A<3) & (A>1)])
